---
title: "Scorpion Study AVC"
author: "Put your name here!"
date: "Fall 2018"
output:
  html_document:
    df_print: paged
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)

```

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->
3.	What percentage of scorpions are found in open area vs in vegetation?

# Methods

we will load in the excel file and take a look at it.

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->
#Results
```{r}
Ziadata <- 
  readXL("Data for bill stat class.xlsx",
   rownames=FALSE, header=TRUE, na="", 
  sheet="Sheet1", stringsAsFactors=TRUE)
```



<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

## Descriptive Results

Are they at war with each other



### Graphical Descriptive Results

```{r}
with(Ziadata, 
  Barplot(Scorpion.Location.standardized, 
  xlab="Scorpion.Location.standardized", 
  ylab="Percent", col=palette()[2], 
  scale="percent"))
```

<!--Graphical results here.  Make sure to show your code.  Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too.  Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question!-->

### Numerical Descriptive Results

```{r}
local({
  .Table <- with(Ziadata, 
  table(Scorpion.Location.standardized))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})
```

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->

## Inferential Results

```{r}
local({
  .Table <- xtabs(~ Scorpion.Location.standardized , 
  data= Ziadata )
  cat("\nFrequency counts (test is for first level):\n")
  print(.Table)
  binom.test(rbind(.Table), alternative='two.sided', p=.5,
   conf.level=.95)
})
```
<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->


# Discussion and Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->

